name: Publishing to NPM
on:
  release:
    types: [published]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: npm install global vue-cli and vue-cli-service
      run: |
            npm install -g @vue/cli vue-cli-service
            
    - name: alfo
      env:
        VUE_APP_MODYO_TOKEN: "{{secret.TOKEN}}"
        VUE_APP_MODYO_BASE_URL: "{{secret.BASE_URL}}"
        VUE_APP_MODYO_HOST: "{{secret.HOST}}"
        VUE_APP_MODYO_NAME: "{{secret.NAME}}"
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test --if-present
    - name: push to modyo
      run: npm run modyo-push
        
