name: Publishing Modyo Cli on NPM
on:
  status
jobs:
  release:
    name: Releasing to NPM Registry
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Versioning
        run : |
          echo $HOME
          echo $GITHUB_WORKFLOW
          echo $GITHUB_ACTION
          echo $GITHUB_ACTOR
          echo $GITHUB_REPOSITORY
          echo $GITHUB_EVENT_NAME
          echo $GITHUB_EVENT_PATH
          echo $GITHUB_WORKSPACE
          echo $GITHUB_SHA
          echo $GITHUB_REF
          echo $GITHUB_HEAD_REF
          echo $GITHUB_BASE_REF

#          git config user.email "operations@modyo.com"
#          git config user.name "Modyo"

#      - name: Authorizing
#        env:
#          NPM_KEY: ${{ secrets.NPM_KEY }}
#        run: |
#          echo "//registry.npmjs.org/:_authToken=$NPM_KEY" > ~/.npmrc
#      - name: Publishing
#        run: |
#          npm publish